name: flutter_icons_helper
description: An helper implementing utility methods for package flutter_icons
version: 0.0.2
homepage: https://github.com/S0NN1/flutter_icons_helper

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_font_icons: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

