name: flutter_icons_helper
description: An helper implementing utility methods for package flutter_icons
version: 0.0.6
homepage: https://github.com/S0NN1/flutter_icons_helper

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_font_icons: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
